routes/web.php
<?php

use App\Http\Controllers\CertificateController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::prefix('certificate')->name('certificate.')->group(function () {
    Route::get('/', [CertificateController::class, 'create'])->name('create');
    Route::post('/', [CertificateController::class, 'store'])->name('store');
    Route::get('/{certificate}', [CertificateController::class, 'show'])->name('show');
});

app/Models/Certificate.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Certificate extends Model
{
    use HasFactory;

    protected $fillable = ['certificate_number', 'course_name', 'student_name', 'completion_date'];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/CertificateController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CertificateStoreRequest;
use App\Models\Certificate;
use App\Services\PDFService;

class CertificateController extends Controller
{
    protected PDFService $PDFService;

    public function __construct(PDFService $PDFService)
    {
        $this->PDFService = $PDFService;
    }

    public function create()
    {
        return view('certificate_form');
    }

    public function store(CertificateStoreRequest $request)
    {
        $data = $request->validated();

        $certificate = Certificate::create($data);

        $pdf = $this->PDFService->generateCertificate($certificate);

        return $pdf->download("certificate-$certificate->id.pdf");
    }

    public function show(Certificate $certificate)
    {
        return view('certificate_details', compact('certificate'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

resources/views/certificate_details.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Certificate Details</title>
</head>
<body>
<h1>Certificate Details</h1>
<p><strong>Certificate Number:</strong> {{ $certificate->certificate_number }}</p>
<p><strong>Course Name:</strong> {{ $certificate->course_name }}</p>
<p><strong>Student Name:</strong> {{ $certificate->student_name }}</p>
<p><strong>Completion Date:</strong> {{ $certificate->completion_date }}</p>
</body>
</html>

resources/views/certificate_form.blade.php
<form method="POST" action="{{ route('certificate.store') }}">
    @csrf
    <input type="text" name="certificate_number" placeholder="Certificate Number" required>
    <input type="text" name="course_name" placeholder="Course Name" required>
    <input type="text" name="student_name" placeholder="Student Name" required>
    <input type="date" name="completion_date" required>
    <button type="submit">Отримати сертифікат</button>
</form>

<style>
    body {
        font-family: 'Arial', sans-serif;
        background-color: #f4f4f9;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
    }

    form {
        background: white;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
    }

    input[type="text"],
    input[type="date"] {
        width: calc(100% - 22px);
        padding: 10px;
        margin-top: 8px;
        margin-bottom: 16px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    button {
        background-color: #007bff;
        color: white;
        border: none;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        border-radius: 4px;
        width: 100%;
    }

    button:hover {
        background-color: #0056b3;
    }
</style>

resources/views/certificate_template.blade.php
<div class="certificate-container">
    <h1>{{ $certificate->course_name }}</h1>
    <p>Certificate: {{ $certificate->certificate_number }}</p>
    <p>Name: {{ $certificate->student_name }}</p>
    <p>Completion date: {{ $certificate->completion_date }}</p>
    <img src="data:image/png;base64, {!! base64_encode($qrCode) !!}" alt="QR Code">
</div>


<style>
    .certificate-container {
        font-family: 'Arial', sans-serif;
        max-width: 600px;
        margin: 40px auto;
        padding: 20px;
        background: white;
        border: 1px solid #ddd;
        box-shadow: 0 0 10px rgba(0,0,0,0.1);
        text-align: center;
    }

    .certificate-container h1 {
        color: #007bff;
        margin-bottom: 10px;
    }

    .certificate-container p {
        color: #333;
        font-size: 16px;
        line-height: 1.5;
    }

    .certificate-container img {
        margin-top: 20px;
    }
</style>